### ISSUE TITLE
Hydra Issue when using train.py and predict.py - DeepCSR

### ISSUE THREAD

**Issue by gaiborjosue** [neuronets/nobrainer-zoo#38]
Hello,

When training and predicting a model with deepcsr I am currently getting an error related to hydra. This is the command I give:
```

python3 predict.py user_config=/om2/user/egaibor/DeepCSR-fork/configs/predict.yaml inputs.mri_id=201818 inputs.mri_vol_path=/om2/user/egaibor/deepcsr/201818/mri.nii.gz outputs.output_dir=/om2/user/egaibor/deepcsr/predict
_debug
```

As seen, I am giving a config file (.yaml), MRI id, MRI vol path, and the outputs directory. However, when running that command I get this error:

```
Error executing job with overrides: ['user_config=/om2/user/egaibor/DeepCSR-fork/configs/predict.yaml', 'inputs.mri_id=201818', 'inputs.mri_vol_path=/om2/user/egaibor/deepcsr/201818/mri.nii.gz', 'outputs.output_dir=/om2/user/egaibor/deepcsr/predict_debug']
Traceback (most recent call last):
  File "/net/vast-storage/scratch/vast/gablab/egaibor/DeepCSR-fork/predict.py", line 111, in predict_app
    cfg = OmegaConf.merge(cfg, user_config)
omegaconf.errors.ConfigKeyError: Key 'hydra' is not in struct
    full_key: hydra
    object_type=dict
```

And this is how my config file looks like:
```
# pass via cli to override configurations
user_config: null

# input configuration
inputs:
  # unique id for the input mri
  mri_id: 201818
  # input mri path
  mri_vol_path: /om2/user/egaibor/deepcsr/201818/mri.nii.gz
  # model weights checkpoint
  model_checkpoint: /om2/user/egaibor/deepcsr/best_model.pth
  # model predicted surfaces
  model_surfaces: ['lh_pial', 'lh_white'] # , 'rh_pial', 'rh_white'

# surface prediction parameters
generator:
  # template bouding box plus some padding
  bbox_size: [192., 228., 192.]
  # resolution of implicit surface volume
  resolution: 512
  # batch size of points to predict implicit surface rpr.
  points_batch_size: 1000000
  # post-processing prediction using connected components
  isrpr_vol_post_process: True
  # smooth implicit surface representation (Gaussian kernel radius)
  isrpr_vol_smooth: 1.0
  # fix topology using nighres
  fix_topology: True  
  # extracted iso-surface. Attention to the used implicit surface representation to train the model. sdf or occupancy in logit space.  
  iso_surface_level: 0.0  

# DeepCSR model configuration
model:
  hypercol: True
  device: 'cuda:0'

# output configuration (ATTENTION it MUST be override from command line to work with hydra log files)
outputs:
  # output directory
  output_dir: /om2/user/egaibor/deepcsr/predict_debug
  # save intermediate files for debugging
  save_all: False

# hydra configurations and log files
hydra:
  run:
    dir: ${outputs.output_dir}
  output_subdir: null
```
